project:
  type: website

website:
  title: "Gaurav Mudbhatkal"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume

format:
  html:
    theme: pulse
    css: styles.css