project:
  type: website
  output-dir: docs
  resources:
    - llms.txt
    - CNAME

website:
  title: "Gaurav Mudbhatkal"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: random.qmd
        text: Side Missions
      - href: resume.qmd
        text: Resume
      

jupyter:
  kernelspec:
    name: python3
    display_name: Python 3
    language: python

format:
  html:
    theme: pulse
    css: styles.css